version: '3.8'

services:
  crypto:
    build: ./crypto_tool
    ports:
      - "16000:16000"  
    networks:
      - nlu_network  # Use a common network
    depends_on:
      - controller
      - marketplaces
    volumes:
      - ./crypto_tool:/app

  controller:
    build: ./controller
    ports:
      - "16100:16100"
    networks:
      - nlu_network  # Use a common network
    volumes:
      - ./controller:/app 

  marketplaces:
    build: ./marketplaces
    ports:
      - "16200:16200"
    networks:
      - nlu_network  # Use a common network
    depends_on:
      - controller
    volumes:
      - ./marketplaces:/app

  pdf_highlight:
    restart: unless-stopped
    build: ./pdf_highlight
    ports:
      - "36001:36001"
    networks:
      - nlu_network
    depends_on:
      - controller
    volumes:
      - ./pdf_highlight:/app

  reverse_image_search:
    restart: unless-stopped
    build: ./reverse_image_search
    ports:
      - "36000:36000"
    networks:
      - nlu_network
    depends_on:
      - controller
    volumes:
      - ./reverse_image_search:/app      

networks:
  nlu_network:
    external: true
